config/routes.rb
OAuth1::Application.routes.draw do
  
  resources :oauth_clients

  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request

  match '/oauth/token',         :to => 'oauth#token',         :as => :token

  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token

  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token

  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize

  match '/oauth',               :to => 'oauth#index',         :as => :oauth

  resource :user_session
  resource :profile
  
  root :to => 'home#show'
  

end

app/controllers/oauth_clients_controller.rb
class OauthClientsController < ApplicationController
  before_filter :login_required
  before_filter :get_client_application, :only => [:show, :edit, :update, :destroy]

  def index
    @client_applications = current_user.client_applications
    @tokens = current_user.tokens.find :all, :conditions => 'oauth_tokens.invalidated_at is null and oauth_tokens.authorized_at is not null'
  end

  def new
    @client_application = ClientApplication.new
  end

  def create
    @client_application = current_user.client_applications.build(params[:client_application])
    if @client_application.save
      flash[:notice] = "Registered the information successfully"
      redirect_to :action => "show", :id => @client_application.id
    else
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @client_application.update_attributes(params[:client_application])
      flash[:notice] = "Updated the client information successfully"
      redirect_to :action => "show", :id => @client_application.id
    else
      render :action => "edit"
    end
  end

  def destroy
    @client_application.destroy
    flash[:notice] = "Destroyed the client application registration"
    redirect_to :action => "index"
  end

  private
  def get_client_application
    unless @client_application = current_user.client_applications.find(params[:id])
      flash.now[:error] = "Wrong application id"
      raise ActiveRecord::RecordNotFound
    end
  end
end

app/views/oauth_clients/_form.html.erb
<%= error_messages_for :client_application %>
<div class="field">
  <label for="client_application_name">Name*</label><br/>
  <%= f.text_field :name %>
</div>
<div class="field">
  <label for="client_application_url">Main Application URL*</label><br/>
  <%= f.text_field :url %>
</div>
<div class="field">
  <label for="client_application_callback_url">Callback URL*</label><br/>
  <%= f.text_field :callback_url %>
</div>
<div class="field">
  <label for="client_application_support_url">Support URL</label><br/>
  <%= f.text_field :support_url %>
</div>

app/views/oauth_clients/edit.html.erb
<h1>Edit your application</h1>
<%= form_for :client_application, @client_application, :url => oauth_client_path(@client_application), :html => {:method => :put}  do |f| %>
       <%= render :partial => "form", :locals => { :f => f } %>
       <%= submit_tag "Edit" %>
<% end %>
<%= link_to 'Show', oauth_client_path(@client_application) %> |
<%= link_to 'Back', oauth_clients_path %>

app/views/oauth_clients/index.html.erb
<div class="flash"><%= flash[:notice] %></div>
<h1>OAuth Client Applications</h1>
<% unless @tokens.empty? %>
<p>The following tokens have been issued to applications in your name</p>
<table>
  <tr><th>Application</th><th>Issued</th><th>&nbsp;</th></tr>
  <% @tokens.each do |token|%>
    <% content_tag_for :tr, token do %>
      <td><%= link_to token.client_application.name, token.client_application.url %></td>
      <td><%= token.authorized_at %></td>
      <td>
        <% form_tag :controller => 'oauth', :action => 'revoke' do %>
        <%= hidden_field_tag 'token', token.token %>
        <%= submit_tag "Revoke!" %>
        <% end %>
      </td>
    <% end %>
  <% end %>

</table>
<% end %>
<h3>Application Developers</h3>
<% if @client_applications.empty? %>
  <p>
    Do you have an application you would like to register for use with us using the <a href="http://oauth.net">OAuth</a> standard?
  </p>
  <p>
    You must register your web application before it can make OAuth requests to this service
  </p>
<% else %>
  <p>
    You have the following client applications registered:
  </p>
  <% @client_applications.each do |client|%>
    <% div_for client do %>
      <%= link_to client.name, oauth_client_path(client) %>-
        <%= link_to 'Edit', edit_oauth_client_path(client) %>
        <%= link_to 'Delete', oauth_client_path(client), :confirm => "Are you sure?", :method => :delete %>
    <% end %>
  <% end %>
<% end %>
<br />
<h3><%= link_to "Register your application", :action => :new %></h3>

app/views/oauth_clients/new.html.erb
<h1>Register a new application</h1>
<%= form_for :client_application, :url => { :action => :create } do |f| %>
   <%= render :partial => "form", :locals => { :f => f } %>
   <%= submit_tag "Register" %>
<% end %>

app/views/oauth_clients/show.html.erb
<h1>OAuth details for <%=@client_application.name %></h1>
<p>
  <strong>Consumer Key:</strong>
  <code><%=@client_application.key %></code>
</p>
<p>
  <strong>Consumer Secret:</strong>
  <code><%=@client_application.secret %></code>
</p>
<p>
  <strong>Request Token URL</strong>
  <code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.request_token_path %></code>
</p>
<p>
  <strong>Access Token URL</strong>
  <code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.access_token_path %></code>
</p>
<p>
  <strong>Authorize URL</strong>
  <code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.authorize_path %></code>
</p>

<p>
  We support hmac-sha1 (recommended) as well as plain text in ssl mode.
</p>
<%= link_to 'Edit', edit_oauth_client_path(@client_application) %> |
<%= link_to 'Back', oauth_clients_path %>